version: '3.8'

services:
  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"
    platform: linux/amd64
  
  mongodb:
    image: mongo:4.4.7
    ports:
      - "27017:27017"
    platform: linux/amd64
  
  auth:
    image: vksssd/intercom-auth
    depends_on:
      - redis
      - mongodb
    ports:
      - "8080:8080"
    platform: linux/amd64

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --label-enable --interval 30
    restart: always
    depends_on:
      - auth
