version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-2204:current
      
jobs:
  build-auth:
    executor: machine-executor
    steps:
      # - setup_remote_docker:
      #     version: 20.10.7
      #     docker_layer_caching: true

      - checkout

      # - restore_cache:
      #     name: Restore build cache
      #     keys:
      #       - go-mod-v1-{{ checksum "go.sum" }}
      #       - go-mod-v1-

      - run:
          name: Go mod tidy
          command: go mod tidy

      - run:
          name: Build application
          command: go build -o intercom ./cmd/main.go

      # - save_cache:
      #     paths:
      #       - /go/pkg/mod
      #     key: go-mod-v1-{{ checksum "go.sum" }}

      - run:
          name: Build and push Docker image
          command: |
            set -e
            docker --version
            docker info
            TAG=$(echo $CIRCLE_SHA1 | cut -c1-7)
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker build -t vksssd/intercom-auth:$TAG .
            docker push vksssd/intercom-auth:$TAG
            docker tag vksssd/intercom-auth:$TAG vksssd/intercom-auth:latest
            docker push vksssd/intercom-auth:latest

services:
  mongodb:
    image: mongo:4.4.7
    expose:
      - "27017"

  redis:
    image: redis:6.2.6
    expose:
      - "6379"

workflows:
  version: 2
  build:
    jobs:
      - build-auth
