version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-2204:current
    # working_directory: /app

jobs:
  build-auth:
    executor: machine-executor
    steps:
      - checkout

      - run:
          name: Go mod tidy
          command: go mod tidy

      - run:
          name: Build application
          command: go build -o auth ./cmd/main.go

      - run:
          name: Build and push Docker image
          command: |
            docker --version
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
            TAG=$(echo $CIRCLE_SHA1 | cut -c1-7)
            docker buildx create --use
            # --platfrom defines for which platfrom it will run with ease
            docker buildx build --platform linux/arm64/v8 -t vksssd/intercom-auth:$TAG .
            docker push vksssd/intercom-auth:$TAG
            docker tag vksssd/intercom-auth:$TAG vksssd/intercom-auth:latest
            docker push vksssd/intercom-auth:latest

services:
  mongodb:
    image: mongo:4.4.7
    ports:
      - "27017:27017"

  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"

workflows:
  version: 2
  build:
    jobs:
      - build-auth
