version: 2.1

executors:
  docker-executor:
    docker:
      - image: docker.io/docker:20.10.7
    working_directory: /app

jobs:
  build-auth:
    executor: docker-executor
    steps:
      - checkout

      - run:
          name: Go mod tidy
          command: go mod tidy

      - run:
          name: Build application
          command: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o auth ./cmd/main.go

      - run:
          name: Build and push Docker image
          command: |
            docker --version
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
            TAG=$(echo $CIRCLE_SHA1 | cut -c1-7)
            docker buildx create --use
            docker buildx build --platform linux/arm64 -t vksssd/intercom-auth:$TAG .
            docker push vksssd/intercom-auth:$TAG
            docker tag vksssd/intercom-auth:$TAG vksssd/intercom-auth:latest
            docker push vksssd/intercom-auth:latest

services:
  mongodb:
    image: mongo:4.4.7
    ports:
      - "27017:27017"

  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"

workflows:
  version: 2
  build:
    jobs:
      - build-auth
